tests: unit: help: add tests for kw --version
Add unit tests for kw version under normal installation.

Also, the repo-mode message is now sent to stderr. That way, it  can  be
easily ignored with a simple  redirection  to  /dev/null.  This  can  be
useful in future integration  tests  which  may  run  kw  in  repo-mode.
Otherwise, the output would always be messed up by the repo-mode message
and have to be filtered out in every test.

Signed-off-by: uwla <uwlalinux@gmail.com>
Signed-off-by: Rodrigo Siqueira <siqueirajordao@riseup.net>
Reviewed-by: Rodrigo Siqueira <siqueirajordao@riseup.net>

diff --git a/kw b/kw
--- a/kw
+++ b/kw
@@ -91,7 +91,12 @@ if [[ "${KW_REPO_MODE}" == 'y' ]]; then
   repo_mode_msg+=$'\t'"KW_PLUGINS_DIR=${KW_PLUGINS_DIR}"$'\n'
   repo_mode_msg+=$'\t'"KW_SOUND_DIR=${KW_SOUND_DIR}"$'\n'$'\n'
   repo_mode_msg+="${SEPARATOR}"
-  say "${repo_mode_msg}"
+
+  # Message is redirected to stderr such that it can be easily ignored if needed.
+  # Otherwise, it could mess up the output expected by  integration  tests  which
+  # are runnning kw in repo-mode and the tests would fail (we may eventually want
+  # such tests because in repo-mode we can execute kw without installing it).
+  say "${repo_mode_msg}" >&2
 fi
 
 function kw()
